/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d8dadc',
        'outline': '#76777d',
        'surface-container-high': '#e6e8ea',
        'primary-container': '#131b2e',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e0e3e5',
        'on-error': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'on-secondary': '#ffffff',
        'inverse-primary': '#bec6e0',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-container': '#497cff',
        'surface-bright': '#f7f9fb',
        'on-surface': '#191c1e',
        'on-tertiary': '#ffffff',
        'surface-container': '#eceef0',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#002113',
        'on-background': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'primary': '#000000',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'background': '#f7f9fb',
        'tertiary-container': '#00174b',
        'on-tertiary-fixed-variant': '#003ea8',
        'secondary': '#006c49',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#00174b',
        'secondary-container': '#6cf8bb',
        'tertiary': '#000000',
        'on-secondary-container': '#00714d',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#b4c5ff',
        'inverse-surface': '#2d3133',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#4edea3',
        'surface-tint': '#565e74',
        'outline-variant': '#c6c6cd',
        'on-primary-fixed-variant': '#3f465c',
        'on-surface-variant': '#45464d',
        'surface': '#f7f9fb',
        'tertiary-fixed': '#dbe1ff',
        'secondary-fixed': '#6ffbbe',
        'on-primary-container': '#7c839b',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'gutter': '24px',
        'unit': '4px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'headline-xl': ['Playfair Display'],
        'headline-lg': ['Playfair Display'],
        'headline-md': ['Playfair Display'],
        'headline-xl-mobile': ['Playfair Display'],
        'body-lg': ['"Source Sans 3"'],
        'body-md': ['"Source Sans 3"'],
        'label-md': ['"Source Sans 3"'],
        'label-sm': ['"Source Sans 3"'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
